### ISSUE TITLE
Renaming/removing module files leads to incorrect states in module list

### ISSUE THREAD

**Issue by nikke234** [Aalto-LeTech/intellij-plugin#110]
Removing/renaming module files causes `.idea/modules.xml` to be out of date. The IDE still thinks the modules are there, which makes the modules show as installed in the course modules list.

**Comment by superseacat** [comment]
tried & worked:
- remove a module folder from OS -> 'error'
- delete a module from project view -> 'download to install'
- remove a library other modules depend on -> 'error in dependencies'
- reinstalling a library other modules depend on after deletion from project view -> makes depending modules valid again ('installed')

tried and unsure if I understand the idea:
- reinstalling a library other modules depend on after deletion from the OS -> makes dependants 'errored in deps', module itself (in module view) 'error'ed, does not reinstall; **a question:** should it reinstall?
- install some modules that depend on O1 (O1 is listed in modules' `.iml`'s); remove O1 (module statuses go into 'error in deps'), O1 itself goes 'error'; reinstall O1; module statuses get back to 'installed'. **a question:** should O1 return to modules' `.iml`? @OlliKiljunen 

non-related observation: `module.xml` takes time to refresh/reload

**Comment by superseacat** [comment]
- delete a single `.jar` inside the scala SDK folder; things just stay as they are. **a question:** is it possible to make them maybe 'readOnly'?
- delete the whole scala SDK folder; O1 and other modules go 'error in deps'
