### ISSUE TITLE
upgrade IDEA target version to latest and briefly check things work

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#133]
otherwise we can only test with the highest target version listed for plugin ( **`2019.3.3`** )

**Comment by superseacat** [comment]
`clean` -> `assemble` -> `runIde` gives the "A+.Menu" error

**Comment by OlliKiljunen** [comment]
For me, it seems to happen when one tries to open the menu too soon after opening a project (could it be: before the indexing is finished?). It may be an issue with this `DumbAware` thing (which I am too dumb to be fully aware of).

**Comment by superseacat** [comment]
but is it at all related to the version upgrade... ? :confused:

**Comment by OlliKiljunen** [comment]
Perhaps our configuration was always "wrong" but the old IDEA version was more forgiving in that sense. Or it can be a bug of new IDEA.
