### ISSUE TITLE
code coverage generator

### ISSUE THREAD

**Issue by OlliKiljunen** [Aalto-LeTech/intellij-plugin#14]

**Comment by OlliKiljunen** [comment]
Forgot to refer the issue on commit message: Commit 89f5a1

**Comment by OlliKiljunen** [comment]
Do we want to require certain level of code coverage of builds to pass? AFAIK this can be easily do. Otherwise, I think there's no much more to do with this task.

**Comment by superseacat** [comment]
> Do we want to require certain level of code coverage of builds to pass? AFAIK this can be easily do. Otherwise, I think there's no much more to do with this task.

80%?
