### ISSUE TITLE
check what Aalto's K8S has to offer

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#15]
in terms of images on Linux (Ubuntu), Windows and MacOS latest (can we find the images, what are the costs etc.)

**Comment by Mankro** [comment]
Some comments even though I don't really know what this is about:

* As far as I know, Aalto has no K8S cluster, but CS IT does. Aalto IT services outside CS IT do not really have any K8S experts.
* Aalto has a contract for Microsoft Azure and ITS has used it for some container needs.
* CSC sells a K8S service to universities, but we don't use it.
* The K8S cluster at CS IT can run Linux containers and A+ currently sends submission grading jobs there. The grading containers are based on Debian and they are hosted in hub.docker.com.
* I don't think that CS IT could run any Mac or Windows containers in K8S, but I don't really know.

**Comment by khappone** [comment]
Hi! Small comment from CSC's side. Our Rahti service (https://rahti.csc.fi/) is free to use for research and education (https://research.csc.fi/free-of-charge-use-cases), for others there is a cost.

As for Windows and Mac mages, I don't know of a container runtime that supports them, as containers are generally tied quite tightly to the linux kernel.

**Comment by superseacat** [comment]
local A+ docker image for both:
* automated testing in travis
* developing against A+ API
