### ISSUE TITLE
Determine if a student has changes in a module when updating a module

### ISSUE THREAD

**Issue by nikke234** [Aalto-LeTech/intellij-plugin#154]
When downloading a module, add the current time to the local course file:
```
"GoodStuff": {
  "id": "abc",
  "downloadedAt": "..."
}
```
To see if a module has been changed, check the last modification time of _every_ file in the module and compare it to the download time (with some tolerance). If the module has been changed, warn the user that updates would overwrite the changes.

**Comment by superseacat** [comment]
- should course file be adjusted on module removal
- should module always pull latest O1

**Comment by nikke234** [comment]
@superseacat 
> should course file be adjusted on module removal

I think the easiest solution is to leave the modules there and just remember that they're not necessarily installed. The IDs get overwritten when the module is downloaded again
