### ISSUE TITLE
create JB account for plugin upload (email group/alias)

### ISSUE THREAD

**Issue by OlliKiljunen** [Aalto-LeTech/intellij-plugin#16]

**Comment by superseacat** [comment]
applied for an exchange email list "intellij-plugin-letech@aalto.fi" - we will register a new JB account with it. and optionally can list the email as a contact in plugin.xml (for contact purposes)

**Comment by superseacat** [comment]
created an account:
* intellij-plugin-letech@aalto.fi
* password (distributed among dev team members)
have a nice developing ;-)

**Comment by superseacat** [comment]
also added dev team members to the list
