### ISSUE TITLE
deployment structure (travis w 2 branches)

### ISSUE THREAD

**Issue by OlliKiljunen** [Aalto-LeTech/intellij-plugin#17]
plugins repo and plugins repo beta

**Comment by superseacat** [comment]
at this point in time, travis build w caching takes longer (uncash + cache the new results) **takes longer, than without caching at all**:

w: https://travis-ci.org/Aalto-LeTech/intellij-plugin/builds/634209097
wo: https://travis-ci.org/Aalto-LeTech/intellij-plugin/builds/634196715
```
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
```
