### ISSUE TITLE
"Turn project to A+ project" should be grayed out IN ALL CASES when it is not applicable

### ISSUE THREAD

**Issue by OlliKiljunen** [Aalto-LeTech/intellij-plugin#183]
In some cases it is grayed out as expected but it should also be when it's clicked but the restart is opted out.

**Comment by nikke234** [comment]
Note on this:  I designed the action to be safe to use multiple times on the same project, so that if a student for an example wants the IDE settings after all, or maybe deleted a project setting etc. It may be useful to have the action available even if the project is already an A+ project.
