### ISSUE TITLE
Project Settings Bug

### ISSUE THREAD

**Issue by nikke234** [Aalto-LeTech/intellij-plugin#197]
Despite being shown in the settings menu, it seems that the project settings aren't actually active. This can be seen by importing `GoodStuff` and opening `Category.scala`, where the IDE complains about `import scala.collection.mutable.Buffer` being unused, which shouldn't happen.

**Comment by OlliKiljunen** [comment]
Interesting. But the settings will be active after restart, right? If there's no easy way to fix this, can we just redefine the workflow to require restart also for project settings (because IDE settings need a restart nevertheless).

**Comment by nikke234** [comment]
Unfortunately not. They aren't active even after invalidating caches and restarting.

To activate the unused import settings, one has to do the following:
`Settings...` -> `Editor` -> `Code Style` -> `Scala` -> `Imports`
Then change the scheme to from IDE to project and press `Apply`.

That apply functionality obviously just calls some IntelliJ code, so doing it programmatically shouldn't be too difficult, but the problem is that it only activates the unused import settings.

I need to find some way to basically reload all project settings, as we can't really know which settings have changed.

**Comment by OlliKiljunen** [comment]
Changing scheme to **Project** modifies **.idea/codeStyles/codeStyleConfig.xml** file:
```
<component name="ProjectCodeStyleConfiguration">
  <state>
    <option name="USE_PER_PROJECT_SETTINGS" value="true" />
  </state>
</component>
```
So should this file be included in **o1_2020_project_settings.zip**?

**Comment by nikke234** [comment]
Nice find! I'll see if that does the trick

**Comment by nikke234** [comment]
That indeed fixes the issue with the unused import settings, and the other settings actually work after all, so this is luckily just a bug on O1-side. Once again, great find :+1:
