### ISSUE TITLE
unite exercises and modules under a single tab

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#203]
* they are the same tab, but separated by a flexible terminator/splitter line
* the name of the tab has a tiny logo of A+ and a written text "A+"

**Comment by OlliKiljunen** [comment]
![Annotation 2020-06-09 131505](https://user-images.githubusercontent.com/6066364/84136266-bb52e180-aa53-11ea-8b21-1a569976b201.png)

**Comment by superseacat** [comment]
both `exercise`s and `module`s should use `JScrollPane`

**Comment by superseacat** [comment]
to check: if **exercises** should have more depth (like also able to expand to show **chapters**) @jsorva
