### ISSUE TITLE
creating an initial layout (i)

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#205]
* button to submit (+2-click) - opposite to downloading a module
* cancel button
* action to submit
* submissions count
* UI form for submission
  * token validation
  * group selection
  * files submitted (changed)

**Comment by OlliKiljunen** [comment]
![Annotation 2020-06-09 131621](https://user-images.githubusercontent.com/6066364/84136328-ce65b180-aa53-11ea-8b43-88bc212930fe.png)
