### ISSUE TITLE
Unit tests fail on some platforms

### ISSUE THREAD

**Issue by OlliKiljunen** [Aalto-LeTech/intellij-plugin#213]
On a Windows development platform, `ApplicationManager.getApplication()` returns `null` when running unit tests, which causes currently 15 tests to fail (in most cases, the error is raised when `PluginSettings` class cannot be initialized because of this).

**Comment by OlliKiljunen** [comment]
This will be fixed when a PR (to be opened soon) related to #185 gets merged. Issue was that some test classes that didn't inherit `PlatformTestCase` accessed `PluginSettings` class. Those accesses are gonna be removed which also solves this issue.

**Comment by OlliKiljunen** [comment]
>This will be fixed when a PR (to be opened soon) related to #258 gets merged
Sorry, that's not gonna happen in #286

**Comment by superseacat** [comment]
on `master` now 😛
