### ISSUE TITLE
link submission/feedback HTML page from the IDE

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#217]
* **direct to A+** - has been discussed as a "quick-and-easy-for-now-solution"
* direct to local browser

**Comment by OlliKiljunen** [comment]
Could [JBCefBrowser](https://github.com/JetBrains/intellij-community/blob/master/platform/platform-api/src/com/intellij/ui/jcef/JBCefBrowser.java) be utilized for rendering feedback inside IDEA?

**Comment by superseacat** [comment]
> Could [JBCefBrowser](https://github.com/JetBrains/intellij-community/blob/master/platform/platform-api/src/com/intellij/ui/jcef/JBCefBrowser.java) be utilized for rendering feedback inside IDEA?

rendering of the HTML by itself is now a big deal, the problem that I see, is, that there is also CSS, that we don't get from the API. so if comparing the way things would look in the A+ Web UI and locally I'd go with the simpler browser option.

**Comment by superseacat** [comment]
what we could do is separate this challenge into two parts, where we first get the "dummy" redirection to the A+ web page, and then, after everything is done and we're happy, we could try this browser feature, that indeed looks curious :cucumber:

**Comment by nikke234** [comment]
Yes, JBCefBrowser would be the way to go, and it is also available and enabled by default starting from 2020.2.

I agree that for now just opening the browser is the way to go, since the feedback without the css looks horrible (although getting the css shouldn't be too tricky).
