### ISSUE TITLE
Error if scala plugin is not installed

### ISSUE THREAD

**Issue by OlliKiljunen** [Aalto-LeTech/intellij-plugin#224]
If Scala plugin is not installed when the project is turned into a A+ project, an error raises. That's because O1Library and consequent;y Scala SDK are auto installed, but installing Scala SDK uses our `ScalaSDK` class which is dependent on Scala plugin to be installed.

Two possible solutions:
**Easy**: Make Scala plugin mandatory so it's installed when our plugin is installed.
**Less easy**:  When a project is turned into a A+ project, first install the required plugins (and restart), before auto-installing modules (O1Library).

**Comment by OlliKiljunen** [comment]
In today's daily meeting, we thought that "Easy" solution would be sufficient at this point (for O1 course) and "Less easy" solution could be implemented in the future (once the plugin is targeted for other courses too).

It should be investigated, though, how does defining Scala plugin mandatory, displays to a user/student who installs our plugin, and if the process of getting mandatory dependency plugins is straightforward enough.

**Comment by superseacat** [comment]
linking this here https://github.com/Aalto-LeTech/intellij-plugin/issues/144

**Comment by superseacat** [comment]
https://intellij-support.jetbrains.com/hc/en-us/community/posts/360009409759--depends-org-intellij-scala-depends-

**Comment by superseacat** [comment]
removed that post to JB forum as irrelevant due to the recent changes in 2020.2
