### ISSUE TITLE
display a course-specific message at the top of the REPL when the REPL launches

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#228]
ask @jsorva what is that message

**Comment by jsorva** [comment]
I'd like to be able to specify the message in the course config file.

**Comment by superseacat** [comment]
https://version.aalto.fi/gitlab/jsorva/o1matsku/-/merge_requests/11

**Comment by OlliKiljunen** [comment]
Commit bd276cb makes it now use `MyScalaLanguageConsole`. The implementation is even quite okay now (follows the architecture, not expected to break on first update).

I'm not sure what is the correct direction to go on from here, so I'll unassign myself of this task. Feel free to call me back if needed.
