### ISSUE TITLE
auto-import in the REPL: run import o1._ and optional module-specific import commands upon REPL launch

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#229]
ask @jsorva what are those commands

**Comment by jsorva** [comment]
The commands should be configurable on a module-by-module basis, presumably by writing them into the course config file.

**Comment by superseacat** [comment]
https://version.aalto.fi/gitlab/jsorva/o1matsku/-/merge_requests/11

**Comment by superseacat** [comment]
https://regex101.com/r/6qGJNV/1 a regex validator
