### ISSUE TITLE
Auto-installed modules sometimes show "Not installed"

### ISSUE THREAD

**Issue by OlliKiljunen** [Aalto-LeTech/intellij-plugin#244]
This bug wasn't completely fixed with #341. So it's reopened.

---

From [a Slack discussion](https://apluslms.slack.com/archives/CSDV9CA31/p1612296643039100) from 2021-02-03:
@OlliKiljunen:
>[...] I think I found the root cause of the "auto-installed show not installed" issue. It's probably because `CourseProjectAction` uses one `Course` object but `MainViewModelUpdater` creates another. The module that see itself installed is not the one that is rendered on the list.

>I tried to "quickly" fix this in two different ways:
>1. make `StateMonitor`s be reused by modules when the `Course` object changes
>2. make `startAutoInstalls` use `Course` from the newly-updated main view model
>Neither of these worked nicely. If you wanna see my code, send a message. But it's probably better try something else (that is, fix it properly).

@nikke234:
>Oh yeah, that's a good find!
>Maybe it's time for an update that just mutates the existing course instance in a thread-safe manner instead of creating new ones. For an example, `CourseProjectAction` could create the main view model, and the scheduled updater would be just responsible for updating the existing view model instead of creating it as well. It would also remove the constant adding and removing of listeners related to each new created course instance. (And it should also make it easier to make the current hacky update preventing mechanism non-static.)

---

## Original description of the issue:

Turn project into A+ project. O1Library is installed but in the list of modules, it still shows "Not installed".

---

This bug actually reflects a more major issue underneath, an issue that could cause more harmful errors (like local changes overwritten without user acceptance when updating modules). Luckily, these errors are unlikely to happen in normal use.

The issue is that when main view model is updated (periodically), a new model object instances are created too. Because we use `stateMonitor`s as concurrency control for module installation, and each model object instance has their own `stateMonitor`, we could end up in a situation where two instances of, say, O1Library module are downloading/installing themselves (into the same directory, that is) at the same time. The if-clause that skips main view model update if some of the components are active, is likely to prevent this from happening but it's not guaranteed.

---

**Easy fix** for this particular case (that auto-installed modules show initially "Not installed"): when starting main view model auto-updater, do it so that it's not run immediately but only after the first cycle 15 minutes.

**Proper fix**: Re-desing. A lot.

I see two possibilities: either make major changes to component installer so that it uses some other kind of concurrency control. Or change main view model updater so that it reuses the existing component objects if there are any. It could be possible to just reuse `StateMonitor`s of them but that would require that the new objects would register themselves as listeners to those state monitors (and the old objects should be unregistered so that they can be GC'ed).

---

A reason why we have this bug: Component installer was designed with such a mindset that there is one-to-one mapping between modules/libraries (domain entities) and `Component` instances representing them. Main view model updater, then again, was designed to create new model objects and just letting the old ones to be garbage collected. This conflict in design principles was noted when the implementation of the latter was first merged, but it was believed (or hoped) not to cause problems.

**Comment by nikke234** [comment]
Wouldn't the easy fix result in the modules list showing as empty for the first 15 minutes, since the main view model updater is also responsible for creating the course instance that gets updated?

Perhaps an even easier fix (albeit definitely not a good permanent solution) would be to make the main view model update and component installation `synchronized` with the same lock? This would achieve the same thing as now (checking if components are active) but with 100% correctness.

Very nice issue description btw

**Comment by superseacat** [comment]
@nikke234 tries his approach, everyone are OK

**Comment by superseacat** [comment]
from UX perspective it's not very critical, as O1 is not supposed to be worked with, and it gets "installed" once any other module (any) is installed

**Comment by superseacat** [comment]
not sure, if related, but when I was testing the now-deleted-logics for `required plugins missing check` I've noticed, that in several cases (did not focus on how to reproduce though), `MainViewModel` was initialized, but say `CourseViewModel` was `null`, despite it was happening where it's shown in the code
```java
  @Override
  public void runActivity(@NotNull Project project) {
    PluginSettings pluginSettings = PluginSettings.getInstance();
    pluginSettings.initializeLocalIdeSettings();
    pluginSettings.ignoreFileInProjectView(MODULE_REPL_INITIAL_COMMANDS_FILE_NAME, project);

    URL courseConfigurationFileUrl = getCourseUrlFromProject(project);
    if (courseConfigurationFileUrl == null) {
      return;
    }

    try {
      Course.fromUrl(courseConfigurationFileUrl, new IntelliJModelFactory(project));
    } catch (UnexpectedResponseException | MalformedCourseConfigurationFileException e) {
      logger.error("Error occurred while trying to parse a course configuration file", e);
      notifier.notify(new CourseConfigurationError(e), null);
      return;
    } catch (IOException e) {
      logger.info("IOException occurred while using the HTTP client", e);
      notifier.notify(CommandAction.getNotificationFor(new NetworkErrorMessage(e)), null);
      return;
    }
    pluginSettings.createUpdatingMainViewModel(project);
//*************************************************************************************************************************************************
// HERE
//*************************************************************************************************************************************************
    ActionUtil.launch(RequiredPluginsCheckerAction.ACTION_ID,
        new ExtendedDataContext().withProject(project));
```
