### ISSUE TITLE
Improve file list in submission dialog

### ISSUE THREAD

**Issue by nikke234** [Aalto-LeTech/intellij-plugin#246]
- [ ] timestamp in a format "last modified 1 minute ago"
- [ ] the bullet points of the submitted files list in the submissions dialog are ever so slightly cut off from the left.

**Comment by superseacat** [comment]
![2021-01-08_15-04](https://user-images.githubusercontent.com/9991098/104018669-dee53280-51c2-11eb-9b1d-746a9aedcfd9.png)
here!
