### ISSUE TITLE
what if "set token" dialog is shown always the first thing on the IDE start-up?

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#275]
after all, users use IDE to submit code...

the reason is that if not, then even if an A+ project, then "Exercises" are empty

**Comment by nikke234** [comment]
I can see the benefit, but I suspect showing a modal dialog at every start up could become very annoying to some users

**Comment by superseacat** [comment]
a checkbox for "don't show this to me until needed (exercise submission)", because, all in all, we expect them to submit from the IDE aren't we?

**Comment by superseacat** [comment]
Not a course project -> token missing (as a label)
refresh action shows setToken dialog when triggered (for exercises ;-) )
