### ISSUE TITLE
Exercises highlight Weeks that are "gone"

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#278]
based on a quick chat: https://apluslms.slack.com/archives/CQ92SAHNY/p1596105553404300 and the fact, that O1 utilizes the concept of Week it might make sense to show if there's no point anymore in doing included assignments (thus I'm almost sure @jsorva will be against as there's also an idea of learning takeaways)

**Comment by jsorva** [comment]
It is important that students can submit even if the deadline has passed. We should not give the signal that "it is impossible" or "makes no sense" to do so. However, it would make sense to mark in the UI which deadlines have already passed. That could be done in the list of assignments and/or (more importantly) the submit dialog, which could warn the user that "you are submitting this thing late".

**Comment by superseacat** [comment]
options: 
* Week [status]
* icon for overdue
* highlight background
* into the submission dialog ("expiring blablabla")

**Comment by superseacat** [comment]
filtering them out AND also the visual icon for the passed: 💀
