### ISSUE TITLE
externalizing settings-properties for the plugin to course config file

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#299]
I have certain worries about the capabilities of the A+ API we will be polling against, so the current thought is to externalize some settings to the course configuration file:
```java
public class SubmissionStatusUpdater {
  ...
  // 10 seconds in milliseconds
  private static final long DEFAULT_INTERVAL = 10L * 1000;

  // 3 minutes in milliseconds
  private static final long DEFAULT_TIME_LIMIT = 3L * 60 * 1000;
```
```java
public class PluginSettings implements MainViewModelProvider {
  ...
  //  15 minutes in milliseconds
  public static final long MAIN_VIEW_MODEL_UPDATE_INTERVAL = 15L * 60L * 1000L;
```
and maybe even
```java
public class PluginSettings implements MainViewModelProvider {
  ...
  //  15 seconds in milliseconds
  public static final long REASONABLE_DELAY_FOR_MODULE_INSTALLATION = 15L * 1000;
```
the benefit as I see is, we can quickly change the number of calls to the API (by reducing their frequency) wo having to wait "up to 2 (two) business days" (that can take JB to review the plugin) + risking some students never update the version... @nikke234 @OlliKiljunen 

and maybe here, maybe definitely?
```java
public class PluginSettings implements MainViewModelProvider {
  ...
  public static final String A_PLUS_API_BASE_URL = "https://minus.cs.aalto.fi/api/v2";
```
```java
public class ScalaSdk extends IntelliJLibrary<PersistentLibraryKind<ScalaLibraryProperties>,
    ScalaLibraryPropertiesState> {

  private static final String URL = "https://scala-lang.org/files/archive/";
```

**Comment by OlliKiljunen** [comment]
|No.|Piece of data|Where to store it|My certainty on issue|
|---|---|---|---|
|1|A+ API URL|Course config file|Very certain|
|2|API polling schedule|Course config file|Could be, a very good proposal|
|3|Course config file polling schedule|Plugin itself|Very certain|
|4|Delay for module installation|Plugin itself|Certain|
|5|Scala SDK download URL|Plugin itself|Pretty certain|

Numbers 3-5 should, however, be stored in a properties file in the plugin's resources.

**Comment by superseacat** [comment]
1. is a must-have

**Comment by superseacat** [comment]
must have is done and merged

**Comment by superseacat** [comment]
after the Week 3 or so (performance)

**Comment by OlliKiljunen** [comment]
Closing for now as we don't have issues.
