### ISSUE TITLE
A+ API must get into our fork of A+

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#311]
- [x] `O1` branch or A+ (to `start_local_a+` ....)
- [ ] ~~add tests~~ there's https://github.com/Aalto-LeTech/intellij-plugin/issues/453 for this now
- [x] re-check the https://github.com/Aalto-LeTech/course-templates

**Comment by superseacat** [comment]
and do test for it

**Comment by OlliKiljunen** [comment]
A+ master branch probably has the changes now. Check that and close.
