### ISSUE TITLE
e2e tests with `runIdeForUiTests`

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#337]
- https://github.com/JetBrains/gradle-intellij-plugin
- ~https://github.com/JetBrains/gradle-intellij-plugin/tree/master/examples/ui-test-example~
- https://github.com/JetBrains/intellij-ui-test-robot/tree/master/ui-test-example

**Comment by OlliKiljunen** [comment]
> This library allows you to write and execute UI tests among IntelliJ Idea. You can test your Plugin.

https://github.com/JetBrains/intellij-ui-test-robot

**Comment by OlliKiljunen** [comment]
We decided to try the approach of #492, except use Kotlin as the scripting language of the UI tests. 

Created issues for next steps and included them in a milestone: https://github.com/Aalto-LeTech/intellij-plugin/milestone/21
