### ISSUE TITLE
Add possibility to make submission group the default for future submissions

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#344]
when the second and further submissions are made do now show the group selection dropdown but maybe just tell smth like: now submitting as a "you and some other guy" group. also then the "network error" notification should be adjusted, as now the case where the groups mismatch (attempt to submit with the "wrong" group) are not possible

**Comment by superseacat** [comment]
a check from the API if it's possible to submit under some other group

**Comment by superseacat** [comment]
**the previous one is the default**

**Comment by nikke234** [comment]
We decided on the following compromise:

Add a check box in the submission dialog that makes the selected group the default group for future submission dialogs (but the group can still be changed from the default).
