### ISSUE TITLE
some extra payload for A+ API calls

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#355]
as proposed by @raphendyr and discussed [here](https://apluslms.slack.com/archives/CQ92SAHNY/p1598430777065200) it would make sense to add some extra data for the calls made for A+ API by the plugin, looking something like this: `intellij/123 o1-plugin/0.4 aalto-o1/0.1 Java/1.10.0`

**Comment by raphendyr** [comment]
The HTTP User-Agent header to be exact.

**Comment by raphendyr** [comment]
I guess some of the values could be part details for a component, like

```
intellij/123 my-plugin/0.4 (o1-2020/0.9; +https://plus.cs.aalto.fi/o1/2020) Apache-HttpClient/x.x.x (Java/x.x.x)
```

**Comment by superseacat** [comment]
https://awstats.sourceforge.io/ for parsing on the A+ http server-side
