### ISSUE TITLE
general logging and monitoring

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#358]
* [ ] informative process logging
* [ ] exception handling unification
* [ ] (optional) performance monitoring

**Comment by Taikelenn** [comment]
Before tackling this issue, consider:
- when should we add messages to logs (unhandled exceptions are already "handled" by IntelliJ with the IDE's error window)
- what logs do we want (exception messages, stack traces, some other data?)
- where should the logs be saved (probably in some easily accessible place)
