### ISSUE TITLE
enabling the IDEA's error/exception reporting mechanism

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#359]
"the plugin developers haven't implemented the feature" (reporting errors from the IDE error monitoring and tracking (an example: https://github.com/Aalto-LeTech/intellij-error-reporting )

**Comment by OlliKiljunen** [comment]
Manual error reporting
vs
Automatic error reporting (requires user's consent)

**Comment by superseacat** [comment]
sent Gurus a message asking if whether we have someplace we could forward the error/exception logs to

**Comment by superseacat** [comment]
this could perhaps be a separate configurable plugin (with A+ Courses plugin) depending on it. the URL to send logs could be coming from the (A+ Courses) plugin configuration file.

CS IT can spawn a separate "box" for us to forward the data into.
