### ISSUE TITLE
solve the sonarcloud mis(t)ery

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#36]
* [x] drop codacy
* [x] unused private field rule to get disabled (check), as important if using the GUI creator

**Comment by OlliKiljunen** [comment]
I added a new annotation `@Binding` that we can use to suppress unused private fields warnings (it also helps co-developers and code reviewers to read the code). Fixed another code smell that Sonar keep moaning of.
@superseacat what needs to be done to drop codacy?

**Comment by superseacat** [comment]
removed codacy repository from the service

**Comment by superseacat** [comment]
works: 
![Screenshot from 2020-01-17 13-24-37](https://user-images.githubusercontent.com/9991098/72609090-c84c2880-392c-11ea-8068-3f1359016553.png)

**Comment by superseacat** [comment]
removed codacy repository from the service ( https://app.codacy.com/gh/Aalto-LeTech )
