### ISSUE TITLE
Make exercise status pending when a submission is made

### ISSUE THREAD

**Issue by nikke234** [Aalto-LeTech/intellij-plugin#364]
Currently the exercise status remains as is after a submission. This can lead to confusion, since the exercise may show the no-points icon even when the student has full points until the exercise list is refreshed. Adding a pending icon after a submission is made makes it clear that a refresh is needed to get the most up-to-date status.

**Comment by OlliKiljunen** [comment]
Related to #410

**Comment by OlliKiljunen** [comment]
Possibly easiest to just refresh the whole tree.

**Comment by superseacat** [comment]
immediately on submission refresh the tree + change the icon to "pending" (invent the icon, clock), and then once the results arrive then change
