### ISSUE TITLE
add logo and glyphs to plugin

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#37]
* [x] add **.svg** logo
* [x] add icons for buttons etc.
* [ ] add also screenshots to the JB's repo

**Comment by superseacat** [comment]
JB's guidelines on visual design:
* https://jetbrains.design/intellij/principles/icons/
* http://www.jetbrains.org/intellij/sdk/docs/reference_guide/work_with_icons_and_images.html

**Comment by superseacat** [comment]
related discussion: https://letech.slack.com/archives/C1ENW24RF/p1578487127016500

**Comment by superseacat** [comment]
https://github.com/JetBrains/educational-plugin/blob/629ad18f0923c7d46966f5c15b664ff7f5ea5ff5/educational-core/resources/icons/com/jetbrains/edu/eduCourseAction.svg

**Comment by superseacat** [comment]
and here are the icons to start with [icons.zip](https://github.com/Aalto-LeTech/intellij-plugin/files/4657261/icons.zip)

**Comment by nikke234** [comment]
https://www.jetbrains.org/intellij/sdk/docs/basics/plugin_structure/plugin_icon_file.html

**Comment by superseacat** [comment]
accent colour: #FF00900

**Comment by superseacat** [comment]
https://github.com/Aalto-LeTech/intellij-plugin/issues/218 leftovers go here
