### ISSUE TITLE
Order of assignments in incorrect

### ISSUE THREAD

**Issue by nikke234** [Aalto-LeTech/intellij-plugin#376]
The assignments are currently sorted based on their ID, which doesn't produce the correct order. There isn't a perfect solution for this since the API doesn't return the assignments in the order that they are in the e-book. For now, we should sort the assignments based on the assignment number included in the HTML URL. Feedback assignments don't have those numbers, so they should be filtered out (or always assume they are the last assignment of a chapter).

**Comment by jsorva** [comment]
If we accept a hacky solution for now, the numbers of the feedback assignments could be scraped from other files or manually added to O1’s course config.

**Comment by nikke234** [comment]
Also worth investigating:
Based on a quick glance it seems like the `/courses/<id>/points/me/` end point has the correct order of assignments. While it's not trivial to apply that order to the assignments fetched from the `/courses/<id>/exercises/` end point, this solution would maintain the correct order for feedback assignments.

**Comment by superseacat** [comment]
> Also worth investigating:
> Based on a quick glance it seems like the `/courses/<id>/points/me/` end point has the correct order of assignments. While it's not trivial to apply that order to the assignments fetched from the `/courses/<id>/exercises/` end point, this solution would maintain the correct order for feedback assignments.

@Mankro @raphendyr @jaguarfi could you please consult us on this? could there be a way to solve this server-side (where it IMO supposed to be)?

**Comment by Mankro** [comment]
Is this the same sorting issue that was discussed in the summer, but Jaakko decided that we don't change A+ at all at this time?
https://github.com/apluslms/a-plus/issues/603

**Comment by nikke234** [comment]
@Mankro Yes this is the same issue. It would be nice to get that end point eventually so that we have a solution that works for any course and not just O1.

**Comment by Mankro** [comment]
Yes, it would be nice, but it probably doesn't fit to the autumn schedule.

**Comment by Mankro** [comment]
A new API endpoint for the exercise/chapter tree will be part of the A+ release v1.9 (June 2021): https://github.com/apluslms/a-plus/issues/603
