### ISSUE TITLE
Error: Token string should not contain spaces

### ISSUE THREAD

**Issue by OlliKiljunen** [Aalto-LeTech/intellij-plugin#377]
#### Describe the bug
When setting the A+ token, a following error may be raised "fi.aalto.cs.apluscourses.model.UnexpectedResponseException: Invalid token header. Token string should not contain spaces.". That is the message sent by A+ server (Django) with non-accepting HTTP response.

#### To Reproduce
?

#### Expected behavior
A token without whitespace should be accepted. Leading and trailing whitespace does not cause the error.

#### Screenshots
?

#### Environment (please complete the following information):
?

#### Additional context
This happens consistently with at least one user. It would be helpful if A+ admins could confirm that their token is capable to do API calls.

Additionally, it would be useful if the user facing this issue could report whether or not the following commands prints `HTTP/1.1 200 OK` as the first line:
```
curl -I 'https://plus.cs.aalto.fi/api/v2/courses/154/points/me/' -H 'Authorization: Token 0000000000000000000000000000000000000000'
```
where `0000000000000000000000000000000000000000` should be replaced with their token.

**Comment by superseacat** [comment]
could not reproduce

**Comment by Taikelenn** [comment]
If the pasted token contains leading/trailing whitespace characters other than space (such as a non-breaking space), they won't be trimmed and this error will occur.
