### ISSUE TITLE
missing "Run" for Scala files

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#381]
#### Describe the bug
some users have reported missing "Run" for Scala files, like `GoodStuff.scala`, when right-clicking it. The nasty part that Scala SDK is OK, and offers to start a REPL.

#### Expected behavior
"Run" is present

#### Screenshots
![photo_2020-09-09_08-26-52](https://user-images.githubusercontent.com/9991098/92558000-3d7ebc00-f276-11ea-815f-e6628da8dee0.jpg)

![photo_2020-09-09_08-24-23](https://user-images.githubusercontent.com/9991098/92557853-e24cc980-f275-11ea-827a-0a4eede83ee3.jpg)

#### Environment (please complete the following information):
 - Operating System: at least Windows

#### Additional context
There's an O1-legend, that this issue appears due to the version of the IDEA (2020.2 works and 2020.2.1 not). However, the re-installation of the SDK works (and, apparently the same happens when the IDE is reinstalled/downgraded).

**Comment by superseacat** [comment]
**steps to temporarily solve:**
remove the "red" SDK from the SDK list
restart IntelliJ IDEA 
install the SDK afresh (like described [here](https://plus.cs.aalto.fi/o1/2020/wNN/intellij/#step-3-5-fetch-the-jdk-toolkit-into-intellij))

**Comment by OlliKiljunen** [comment]
Considering mentioning manual run configuration in course materials.
