### ISSUE TITLE
REPL opening approach to be reviewed

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#386]
"Noticed something that maybe doesn't literally count as a bug, since we didn't specify the expected behavior, but was puzzling for a bit: it seemed like my REPL was not starting in the right module: no matter which module I selected, the REPL always launched in O1Library. Then I realized that I was in the Project Files view instead of the usual — but nearly identical-looking — Project view. And selecting modules in Project Files confusingly had no impact on the REPL launch."

https://apluslms.slack.com/archives/CQ92SAHNY/p1600072923362300

**Comment by OlliKiljunen** [comment]
Message user "no module was selected, defaulted to O1Library" + possibly instructions how-to

**Comment by OlliKiljunen** [comment]
Happens in some other situations too?

**Comment by superseacat** [comment]
could not reproduce
