### ISSUE TITLE
a notification if a known (module) dependency is missing

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#387]
if the module is removed, the record is also removed from the corresponding .iml file, but if the dependent module like O1Lib or S2Lib gets added again, then it's not in the initial IML anymore...

**Comment by OlliKiljunen** [comment]
dependencies listed either in course config file or stored locally when module is first imported

**Comment by superseacat** [comment]
#291

**Comment by OlliKiljunen** [comment]
Possibly after or at the same time with #461
