### ISSUE TITLE
Opening a browser doesn't work in some (not officially supported) platforms

### ISSUE THREAD

**Issue by OlliKiljunen** [Aalto-LeTech/intellij-plugin#403]
Opening a browser from a link in the event viewer (probably elsewhere too) causes error in some non-desktop environments. The links should be handled in the same way as IntelliJ's own "Open in browser" actions.

**Comment by superseacat** [comment]
prefer Intellij's `BrowserUtil.browse()` as in https://github.com/Aalto-LeTech/intellij-plugin/pull/470#discussion_r557126840
