### ISSUE TITLE
shadow points (late assignments)

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#405]
One small detail: if exercises are submitted late, they get zero points and a red X is shown. The exercise can however be correctly solved. I’d suggest that in case of a zero score after the weekly deadline, the symbol could be a clock and its color something more neutral than red. (gray/orange/yellow/blue) or :ghost: 

https://apluslms.slack.com/archives/CQ92SAHNY/p1601459651020900

**Comment by OlliKiljunen** [comment]
Easier option: only one icon for "late submission", no points taken into account

**Comment by superseacat** [comment]
O1 Specific -> need to consider futher
