### ISSUE TITLE
Wrong type for Week 6 Assignment 27 (Animals 4)

### ISSUE THREAD

**Issue by Tuulos1** [Aalto-LeTech/intellij-plugin#409]
#### Describe the bug
A+Courses mark Week 6 Assignment 27 (Animals 4) as an assignment that is done and returned through IntelliJ / A+ Courses while it's in reality done through the course website at aalto.fi.

#### Environment (please complete the following information):
 - Operating System: Windows 10
 - IntelliJ IDEA 2020.2.2 (Community Edition)
 - Version of A+ Courses plugin: Newest I assume as the plugin doesn't show what version it is under About the A+ Courses Plugin window and IntelliJ doesn't find a new update for it.

**Comment by nikke234** [comment]
I can confirm this issue. Thanks a lot for reporting it! We will fix it in the near future.

**Comment by OlliKiljunen** [comment]
Similar to #331

**Comment by nikke234** [comment]
Fixed, thanks once again :+1:
