### ISSUE TITLE
decide on versioning

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#426]
pros and cons (2020.2....)?

**Comment by nikke234** [comment]
Some pros:
  + Consistent with IntelliJ versioning; it's simple to tell students to install IntelliJ 2020.2.x and A+ Courses 2020.2.x.
  + Also consistent with the versioning of some popular IntelliJ plugins, e.g. Scala plugin.

Cons:
  + We lose one number. Currently the minor number is used for bug fixes and new features, while the major number is intended for breaking changes (in particular, breaking changes in the course configuration format, which is really the only "public API" of the plugin). For an example, 1.6 and 1.7 should work with the same configuration file, but 2.0 might not. With the suggested versioning scheme, the first two numbers come directly from the IntelliJ version, and only the last number would be left for plugin features/patches.
  + The plugin functionality isn't (almost) at all tied to IntelliJ versions. For an example, the plugin is compatible with both IntelliJ 2020.1 and 2020.2 (although it was never released for 2020.1). When a new IntelliJ version comes out and our plugin is still compatible with it, we have two choices: tell students to install a plugin version that doesn't match IntelliJ's version number (and loose the benefit of consistent versioning), or make a "pseudo-release" with the version number bumped.

**Comment by OlliKiljunen** [comment]
About the first con: we don't have to stay in `{number}.{number}` pattern. We can have `{intellij-version}.{major}.{minor}` (where `intellij-version` can be either of form `2020.3` or `203`, whichever we like). I'm afraid there won't be any compability between versions released so far and versions released from now on anyways (should there be?)

**Comment by nikke234** [comment]
I mean the compatibility of a single plugin version with multiple future IntelliJ versions. The example with 2020.1 and 2020.2 highlight that it happens, but I'm not referring to any current versions

**Comment by nikke234** [comment]
You're right about the first con, but then the consistency with IntelliJ versions would at least partially be broken.

**Comment by superseacat** [comment]
![Screenshot from 2021-01-09 12-59-37](https://user-images.githubusercontent.com/9991098/104089889-32b35280-527b-11eb-9496-631e3ca19dad.png)

so I'm favoring the common approach (like Scala Plugin does): `2020.3.x`, and if the version of the plugin is **100%** compatible with some other major version of the Platform, then we release an additional version of our plugin for it. btw, I think we need to take this matter (multiple majors's supported) into consideration in #449

**Comment by nikke234** [comment]
Related to this: the new plugin version with multi-course support will be compatible with both 2020.2 and 2020.3, so we would then already make two releases

**Comment by nikke234** [comment]
Based on further discussions on slack, we agreed to continue with the current versioning, so I'm closing this
