### ISSUE TITLE
get data on users OSs and payload data from HTTP logs

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#427]
- [x] get data for OSs
- [x] get payload data (https://github.com/Aalto-LeTech/intellij-plugin/issues/355)
- [ ] consider creating the version update progress chart from mapping the release dates and the payload data together

**Comment by Mankro** [comment]
@superseacat Could elaborate what you mean?

We discussed HTTP server logs in the autumn. The idea was to draw statistics about different User Agents used against the A+ server and API. This idea has been buried under other work. We must prioritize other things. This topic is not urgent.

Is there something else?

**Comment by superseacat** [comment]
> We discussed HTTP server logs in the autumn.

this was implemented on our side in #355, so the logs should not actually contain the extra piece of data. we would like to see and perhaps analyze it. I assume, that you may not have the resource to do the analysis, so one of the options I see we get access to the (part of) HTTP logs that contain the data under discussion and process it ourselves. What do you think? @Mankro

**Comment by Mankro** [comment]
My team tried to push this topic to CS IT. Maybe they are busy too. We talked many times in the autumn 2020. @jkotimak could you comment? @superseacat you should make guru ticket and CC me, please.

**Comment by superseacat** [comment]
based on the latest data for the duration of O1/2020 in Google Analytics, the users' OS distribution is the following (aggregated per OS, based on @Mankro 's exported report):

OS | %
-- | --
Windows | 70%
Mac | 25%
Linux | 4%

**Comment by superseacat** [comment]
> |OS|	%|
>|---|---|
> |Windows |**68%**|
> |Mac	   |**28%**|
> |Linux	   |4%|

updated values for aggregated per OS and recalculated accordingly stats retrieved from GA (for September 2020)

**Comment by superseacat** [comment]
current status of the task: CS IT will configure a cron job that would send purified HTTP logs to the team's email weekly

**Comment by superseacat** [comment]
@Aalto-LeTech/apluscourses-plugin-team check your emails, but I'm satisfied now (just make sure the reports will arrive regularly 🤣
