### ISSUE TITLE
Contact Scala plugin team about ScalaConsoleRunConfiguration

### ISSUE THREAD

**Issue by OlliKiljunen** [Aalto-LeTech/intellij-plugin#429]
Our class `ReplConfiguration` in **ReplAction.scala** extends Scala plugin's `ScalaConsoleRunConfiguration` class. In Scala plugin's source, there is a comment related to that class (added [in June](https://github.com/JetBrains/intellij-scala/commit/f1c562147606edf1b39921bddeb051a9bfa5a58d)):
```
/**
 * Run configuration with a single purpose: run Scala REPL instance in a internal IDEA console.
 * <br>
 * The class is not intended to be reused/extended in other plugins.
 * If you want to reuse some of the class functionality, please contact Scala Plugin team
 * via https://gitter.im/JetBrains/intellij-scala and we will extract some proper abstract base class.
 */
```

We should do what it says and contact them about this.

**Comment by superseacat** [comment]
https://gitter.im/JetBrains/intellij-scala?at=6033995f47585464db94b602 @nikke234 @OlliKiljunen

**Comment by superseacat** [comment]
also added a post to the forum: https://intellij-support.jetbrains.com/hc/en-us/community/posts/360010506040-If-you-want-to-reuse-some-of-the-class-functionality-please-contact-Scala-Plugin-team

**Comment by superseacat** [comment]
it seems, that the approach at JB Scala team is a bit different (from e.g. template team). They wish us to create a PR with the information about the endpoints (extension points) we need. perhaps there are other ways too, but the ball is on our side, and PR is claimed to be the fastest to get processed way. @OlliKiljunen @nikke234
