### ISSUE TITLE
integrate course build files into our scopes

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#431]
like:

- https://version.aalto.fi/gitlab/oseppala/studio2/-/blob/k2021dev/projects/create_s2_course_config.py
- https://version.aalto.fi/gitlab/oseppala/studio2/-/blob/k2021dev/projects/Projektien_pakkaus.py

THINK ABOUT COURSE TEMPLATE THAT SUPPORTS THE PLUGIN

**Comment by superseacat** [comment]
also comment on the build script file **better**

**Comment by superseacat** [comment]
O1 & S2 specific

**Comment by nikke234** [comment]
I suggest we close this issue:

- I wrote the scripts only to make it more convenient to maintain the course configuration file for O1. They are very course specific and require a very specific structure, which our plugin does not. They were not originally intended to be used by any other courses.
- The course configuration file should be (and should stay) manageable without these helper scripts.
