### ISSUE TITLE
ordering of the assignments in the Assignment subview is incorrect

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#434]
hm... looks a bit familiar @Mankro @nikke234 , isn't it?

![assignments_ordering+](https://user-images.githubusercontent.com/9991098/102385788-f02d8b80-3fd6-11eb-94de-d71124b44628.png)

**Comment by Mankro** [comment]
How is this relevant to me? If the sorting is based on alphabetical order, then make sure that the course content does not have multiple exercises that start with "Exercise 2".

**Comment by superseacat** [comment]
https://github.com/Aalto-LeTech/intellij-plugin/issues/435 will solve this
