### ISSUE TITLE
something is fishy with the assignments NUMBERING in Round 15 - part A

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#435]
please, check the numbering of the assignments in **Round 15 - part A**

![ordering_](https://user-images.githubusercontent.com/9991098/102386232-7fd33a00-3fd7-11eb-96b9-2c006875e36f.png)

![assignments_ordering+](https://user-images.githubusercontent.com/9991098/102385976-28cd6500-3fd7-11eb-9dfe-aba5ec0e3e75.png)

**Comment by superseacat** [comment]
shall we try
```json
 "html_url": "https://plus.cs.aalto.fi/studio_2/k2021dev/k14/osa03/k14_osa03_feedback/",
```
as a `String` to sort the exercises/assignments

**Comment by OlliKiljunen** [comment]
> shall we try
> 
> ```json
>  "html_url": "https://plus.cs.aalto.fi/studio_2/k2021dev/k14/osa03/k14_osa03_feedback/",
> ```
> 
> as a `String` to sort the exercises/assignments

Possibly more robust solution: split using `/` as the separator, then sort by parts `k14`, `osa03`, `k14_osa03_feedback`
