### ISSUE TITLE
something is fishy with the assignments SUBMITTABILITY in Round 15 - part A

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#436]
almost sure, that some of these assignments (**Round 15 - part A) must be submittable**

![assignments_ordering+](https://user-images.githubusercontent.com/9991098/102386116-5a463080-3fd7-11eb-9879-a29ddda57424.png)

**Comment by superseacat** [comment]
the solution that seems to work (@oseppala has 20 submissions):
```java
    /**
     * Returns {@code true} if the exercise is submittable from the plugin, {@code false} otherwise.
     */
    public boolean isSubmittable() {
        // O1_SPECIFIC
        String name = getPresentableName();
        int maxSubmissions = getModel().getMaxSubmissions();
        return name.length() > "Assignment xx (".length()
                && !"Assignment 1 (Piazza)".equals(name)
                && !"Assignment  debugger".equals(name)
                && (maxSubmissions == 10 || maxSubmissions == 0 || maxSubmissions == 20);
    }
```

**Comment by superseacat** [comment]
0 for non-submittables
5 for quizzes
> 5 for the others @oseppala

**Comment by superseacat** [comment]
**a custom submittability check must be created once @oseppala has set up initial exercises for the course**

**Comment by superseacat** [comment]
what if all the assignments are submittable by default, and then the teacher only marks the non-submittables

**Comment by OlliKiljunen** [comment]
> 
> 
> what if all the assignments are submittable by default, and then the teacher only marks the non-submittables

Suggestion from the meeting:

In the course config file: an assignment is submittable if `exerciseModules` contains the assignment. For assignments without basecode, add empty JSON object `{}` there for the assignment's id to make it submittable.
