### ISSUE TITLE
where should the "FlatSpec" come from?

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#438]
![2020-12-16_20-01](https://user-images.githubusercontent.com/9991098/102387868-9da19e80-3fd9-11eb-8405-29c9bce12820.png)

**Comment by oseppala** [comment]
ScalaTest. I haven't yet added any of the dependencies, so it's a bit early to check them.

**Comment by superseacat** [comment]
this works
![Screenshot from 2021-01-07 15-33-31](https://user-images.githubusercontent.com/9991098/104281497-45fe3200-54b6-11eb-925b-000bedf93d83.png)
