### ISSUE TITLE
need some indicator to highlight the S2Lib installation process

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#466]
as it takes quite long before anything actually starts to happen on the UI (at least in the case of S2Lib which is about 30MB)

**Comment by OlliKiljunen** [comment]
Does it say "Downloading..." in the modules list though? I agree that might not be enough.

**Comment by superseacat** [comment]
https://user-images.githubusercontent.com/9991098/104424326-e53f2a00-5587-11eb-93ed-210f082237f4.mp4

**Comment by OlliKiljunen** [comment]
What's the situation with this?

**Comment by jaakkonarhi** [comment]
The video is outdated, just needs loading bar
