### ISSUE TITLE
Automatically use macOS keymap from IDE settings

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#468]

**Comment by OlliKiljunen** [comment]
Is this about imported IDE settings of O1? @superseacat @nikke234 ?

**Comment by superseacat** [comment]
and mixing with the macOs defaults, yess

**Comment by OlliKiljunen** [comment]
Ok, so @Taikelenn or whoever implements this:

When a project is turned into A+ project, the plug-in may import IDE settings defined by the teacher of the course. These settings may include keymaps.

In O1 course's imported settings (that you can find [here](https://grader.cs.aalto.fi/static/O1_2020/projects/o1_2020_ij_settings.zip)), there are currently two keymaps: default one and one designed for MacOS. (Note: default one is set by default to all users, including MacOS users. And anyone can change between keymaps.)

Now what should be done, is to check that MacOS keymap in the O1 settings does not "get mixed" with the Mac's default key shortcuts but that the key combos defined there work as they should on Mac.

**Comment by nikke234** [comment]
I think the key here was that the plugin should automatically use the MacOS keymap from the settings, if it is present. The O1 MacOS keymap is fine, but it needs to be set automatically.

**Comment by nikke234** [comment]
Quoting from the [O1 FAQ](https://plus.cs.aalto.fi/o1/2020/wNN/faq/#im-on-a-mac-computer-and-intellij-doesnt-type-characters-such-as-the-dollar-and-square-brackets-what-to-do):
> (We’ll be updating the A+ Courses plugin to take care of that automatically, but for now this is the best solution. Sorry about the extra trouble.)

**Comment by OlliKiljunen** [comment]
How that could or should be done? If it's too tricky thing, we should consider if it's worth it.

**Comment by nikke234** [comment]
If you download the ZIP for O1 settings and try to import it, you will be presented with a list of checkboxes for selecting what parts from the settings you wish to import. One of those is the keymap. So detecting the settings present in the ZIP should be doable without us manually parsing the settings. The "magic" happens here:
https://upsource.jetbrains.com/idea-ce/file/idea-ce-4b94ba01122752d7576eb9d69638b6e89d1671b7/platform/configuration-store-impl/src/ImportSettingsAction.kt

Given the priority and impact of this issue, I would say that the bar for not implementing it has to be very high (i.e. completely unacceptable complexity or fragile implementation).

**Comment by nikke234** [comment]
An alternative (and much easier on our side) idea that came to my mind: have separate IDE settings for macOS and other operating systems. The settings URLs are already stored in a map, so adding another URL for macOS IDE settings would be very easy.
