### ISSUE TITLE
Investigate options for CI

### ISSUE THREAD

**Issue by OlliKiljunen** [Aalto-LeTech/intellij-plugin#471]
Our much loved Travis has been turned into a paid service and we are out of free credits there. What should be done to keep our CI running?

Some options:
- pay Travis ($69/month for one concurrent build job, other pricing options too)
- move to another CI system (Aalto GitLab? Other?)
- something else

Investigate!

**Comment by superseacat** [comment]
@superseacat is to ask Travis

**Comment by nikke234** [comment]
GitHub actions seems to be completely free for open source projects, so I suggest we switch to that, especially since our release already happens through GH actions.

**Comment by OlliKiljunen** [comment]
But GH actions cannot run tests or SonarScanner, can they?

**Comment by nikke234** [comment]
Why could they not run tests?

**Comment by nikke234** [comment]
SonarScanner is a good question though

**Comment by nikke234** [comment]
I at least found a SonarScanner GH action, so that should be possible as well

**Comment by OlliKiljunen** [comment]
> Why could they not run tests?

I don't know. I just didn't expect them to give away computing resources that generously (more than making some simple https queries to external services). But I might have been wrong. Worth investigating, I guess.

**Comment by nikke234** [comment]
As far as I know tests is completely fine and a common use of GH actions. The only thing I haven't been able to figure out whether free for open source means unlimited minutes or if it has the 2000 free minute limit that _private_ repos have.

**Comment by OlliKiljunen** [comment]
Should this be closed now or only later? What is there still to do?

**Comment by superseacat** [comment]
> Should this be closed now or only later? What is there still to do?

I've agreed I write an email to Travis and @jsorva wanted to take a look as well

**Comment by superseacat** [comment]
migrated to GH actions, but some things still need to be handled: #506, #507
