### ISSUE TITLE
Design the UI flow for changing/undoing course selection

### ISSUE THREAD

**Issue by OlliKiljunen** [Aalto-LeTech/intellij-plugin#489]
If a user accidentally selects a wrong course when turning a project into A+ project, how could they undo that selection afterwards?

This issue is opened as a design issue only, but can cover the implementation too, if so decided. Otherwise, follow-up issue(s) can be created once it is known how it will be implemented.

**Comment by nikke234** [comment]
Currently the only (not so nice) solution: create a new project (since the course selection isn't shown again if you use "Turn Project Into A+ Course Project" in a course project).

**Comment by jaakkonarhi** [comment]
![image](https://user-images.githubusercontent.com/34682147/121175755-1df7dc80-c864-11eb-950c-83ad637c3005.png)
how about this

**Comment by jaakkonarhi** [comment]
pawel likes this
