### ISSUE TITLE
Loading bar

### ISSUE THREAD

**Issue by jaakkonarhi** [Aalto-LeTech/intellij-plugin#519]
It would be nice to have a loading bar for things like fetching modules and exercises, and downloading modules (#466)

Here's mockups

![image](https://user-images.githubusercontent.com/34682147/107382795-f59be380-6af8-11eb-8942-482cd226825e.png)
This text could be replaced with a loading bar, since it isn't relevant after the A+ token is already set

![image](https://user-images.githubusercontent.com/34682147/107382896-16fccf80-6af9-11eb-98c8-2f1272d099a9.png)
A progress bar could also go down here and be used for everything that needs loading

**Comment by jaakkonarhi** [comment]
Can the content-length be read from a html response before getting all the data? That could be used for the bar

**Comment by jaakkonarhi** [comment]
![image](https://user-images.githubusercontent.com/34682147/107384441-a8207600-6afa-11eb-86b1-f9fc4357772b.png)
here's an acid pink bar if you're into that

**Comment by superseacat** [comment]
> here's an acid pink bar if you're into that

can the bar have rounded corners as like IDEA's?

**Comment by jaakkonarhi** [comment]
![image](https://user-images.githubusercontent.com/34682147/107492111-b4f1a800-6b94-11eb-96ab-2cb05c1ffa14.png)
like the intellij bar
