### ISSUE TITLE
IDE act: Design the assignment description language + some example assignments

### ISSUE THREAD

**Issue by OlliKiljunen** [Aalto-LeTech/intellij-plugin#562]

**Comment by OlliKiljunen** [comment]
A sketch for the description language:
```json
"tutorials": {
  "<assignment id>": {
    "name": "<assignment name>",
    "task": [
      {
        "instruction": "<instruction text>",
        "assume": [
          {
            "_component": "<highlighted component>",
            "_highlight": "<is highlighted>",
            "_info": "<info text>",
          }
        ],
        "assert": [
          {
            "_event": "<event name>",
          }
        ]
      },
    ]
  }
}
```

Here's an example that shows how @jaakkonarhi's example on #561 could be written:
![image](https://user-images.githubusercontent.com/6066364/109650779-61a4c100-7b66-11eb-9d95-3c8d811526f2.png)

**Comment by superseacat** [comment]
how about this existing DSL: https://www.jetbrains.com/help/education/meet-yaml-format.html ?
and overall the approach: https://www.jetbrains.com/help/education/framework-lessons-guide-for-educators.html#e8d7b063 ?
@jsorva
