### ISSUE TITLE
Check that everything work with Scala 3 (current pre-release)

### ISSUE THREAD

**Issue by OlliKiljunen** [Aalto-LeTech/intellij-plugin#566]

**Comment by stellatsv** [comment]
Check Scala SDK installation.

**Comment by OlliKiljunen** [comment]
Apparently, Scala plugin doesn't really support Scala REPL for Scala 3 (yet). This is what happens:

```
Error: Could not find or load main class scala.tools.nsc.MainGenericRunner
Caused by: java.lang.ClassNotFoundException: scala.tools.nsc.MainGenericRunner

Process finished with exit code 1
```

Even with [Scala 3 Example Project](https://github.com/scala/scala3-example-project) running REPL with "Scala REPL" command gives the same result. (Because the example project is a sbt project, running REPL with `sbt console` is possible but the UI for that in IDEA is much worse and also buggy.)
