### ISSUE TITLE
IDE act: Research exisiting tutorial-like solutions

### ISSUE THREAD

**Issue by OlliKiljunen** [Aalto-LeTech/intellij-plugin#581]
Search the www to find what kind of tutorial-like solutions there are for IntelliJ. Study their:
- UI design
- software design (if open source)

Research questions:
- Do existing solutions have such design ideas we could find useful to adopt?
- Would it be feasible to base our implementation on some existing software component / framework?

**Comment by stellatsv** [comment]
There is this [plugin](https://plugins.jetbrains.com/plugin/8554-ide-features-trainer) "IDE Features Trainer" from IntelliJ, the code is available [here](https://github.com/JetBrains/intellij-community/tree/fefba5b419a659f75b27c863c368d4a0aae78d80/plugins/ide-features-trainer).
