### ISSUE TITLE
Properly pluralize text about module updates

### ISSUE THREAD

**Issue by nikke234** [Aalto-LeTech/intellij-plugin#605]
Currently the text in the notification of module updates tries to combine the cases of a single module and multiple modules as follows:
> There are newer version(s) of the following course module(s) available

However, the singular version is incorrect:
> There are newer version of the following course module available.

It would probably be easier to have separate texts for both cases.

**Comment by Taikelenn** [comment]
How about:
> There is a newer version of the following course module(s) available:
Different modules might have different versions, but the user only needs to know that they are outdated

**Comment by nikke234** [comment]
> How about:
> 
> > There is a newer version of the following course module(s) available:
> 
> Different modules might have different versions, but the user only needs to know that they are outdated

I think that might still slightly incorrect, because "version" should be in plural form if "module" is in plural form. At least I interpret "there is a newer version of the following course modules available" as saying that all of the modules have the same newer version, but I guess that's what you also meant by saying that the user only cares about them being outdated, not about htem having different versions.
