### ISSUE TITLE
refactoring the code after Sprint #3

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#91]
identify shortcoming and issues we have and **want** to fix. come out with the desired architecture.

the idea is to check that the code is:
* readable
* understandable
* uniform
* conforms to the previously agreed style and architecture (well-structured)

**Comment by superseacat** [comment]
perform the IJ's static code analysis tool: https://www.jetbrains.com/help/idea/running-inspections.html#run-inspections-manually and then fix where feasible

**Comment by superseacat** [comment]
https://github.com/Aalto-LeTech/intellij-plugin/pull/193/files/e777657f3f3430cdcbfa7f48c43fee6dd7280dcf..46aa6b7610b988cdca15e45b1c888c883393456b#r434051373

**Comment by OlliKiljunen** [comment]
Related to #366

**Comment by superseacat** [comment]
this legendary ticket must go, more detailed ones will be created!
